version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: no
    environment:
      - POSTTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
